### ISSUE TITLE
Assets we require

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-unicef-wcaro#10]
Login
- [ ] Login icon

Family register
 - [x] Home icon
 - ~~Sort icon (up and down icon)~~ RW: recently removed and replaced with a switch for a "show due only" filter
 - [x] Due only switch/toggle
 - [x] Job aid icon
 - [x] boy child
 - [x] girl child
 - [x] pregnant mother
 - [x] home
 - [x] scan qr
 - [x] add family 
 - [x] job aids
 - [x] activity tab 

Add member dialog/popup
- [x] Under 5 years child
- [x] Other family member

Family profile
 - [ ] profile avatar for family
 - [ ] profile avatar for family members 
 - [ ] profile avatar for U5 children
 - [x] go to member icon (-->)
 - [ ] edit icon for the floating button

Forms
- [x] all of the visit form icons (Immunization - oral and injection
Exclusive Breastfeeding
MNP packs
Vitamin A
Deworming
Dietary Diversification
MUAC
Diarrhea and ORS/Zinc provided
Sleeping under LLITN
Development milestones
Stimulation skills of caretaker
Early learning program)

BA Family register
- [ ] child icons (red and navy blue)
- [ ] mosquito 
- [ ] pregnant mother
- [ ] mother with baby
- [ ] notification/warning icon

**Comment by rowo** [comment]
@keymane I added some of the form illustrations into the xxhdpi 

<img width="505" alt="screen shot 2018-12-17 at 10 57 48 pm" src="https://user-images.githubusercontent.com/1584163/50131226-32d4f580-024f-11e9-95fa-588832e21232.png">

**Comment by cagulas** [comment]
@rowo @mahmud6390 from mPower needs the 1 yr and 2 yr fully immunized icons now. We can't find these in the assets folder you've provided so far.

**Comment by cagulas** [comment]
Closing this, as I think it's complete.
