### ISSUE TITLE
Editing of visits increments

### ISSUE THREAD

**Issue by mlberg** [OpenSRP/opensrp-unicef-wcaro#102]
If you complete an initial child form.  If will ask you for the child's second deworming, mnp, vit a 

etc.  I think it's treating it like a second visit.  So each time you click edit things increment.  Logic should be you are editing the first visit still.

<img width="541" alt="screen shot 2019-02-05 at 3 36 43 pm" src="https://user-images.githubusercontent.com/42673455/52280293-df804900-295b-11e9-857d-1e64e9201d16.png">

**Comment by cagulas** [comment]
Yea, I don't think editing is implemented yet.

**Comment by mlberg** [comment]
Confirming this is happening.   This feels pretty high priority over some of the other items.

See how Vit A increments. 

If editing is not supported I suggest we remove the edit link for now.

<img width="611" alt="screen shot 2019-02-14 at 12 19 44 pm" src="https://user-images.githubusercontent.com/42673455/52804862-4637ed80-3053-11e9-888d-359d2b856478.png">

<img width="615" alt="screen shot 2019-02-14 at 12 20 25 pm" src="https://user-images.githubusercontent.com/42673455/52804874-4c2dce80-3053-11e9-943c-f21c18aa0fd8.png">
<img width="613" alt="screen shot 2019-02-14 at 12 20 58 pm" src="https://user-images.githubusercontent.com/42673455/52804899-58b22700-3053-11e9-9c9f-a4f5b75bccad.png">

<img width="611" alt="screen shot 2019-02-14 at 12 20 44 pm" src="https://user-images.githubusercontent.com/42673455/52804895-54860980-3053-11e9-92cd-0798149d7f65.png">

**Comment by cagulas** [comment]
We have removed the edit link for now, so this scenario is not allowed in the current release. We will put back the edit button once the edit functionality is implemented.
