### ISSUE TITLE
Form font size

### ISSUE THREAD

**Issue by mlberg** [OpenSRP/opensrp-unicef-wcaro#103]
<img width="542" alt="screen shot 2019-02-05 at 3 42 49 pm" src="https://user-images.githubusercontent.com/42673455/52280693-bf9d5500-295c-11e9-9121-a00ebbd1baa1.png">

This is from genymotion so I don't know if the font looks this small on a phone. In general, I think we should really blow the font size up on the questions in the forms.  This looks small.  For CHWs we really need to emphasize big, easy visibility, use of images where possible.

**Comment by cagulas** [comment]
@mberg this issue is out of date with the latest releases, so I'm going to close it and create a new issue for the formatting.
