### ISSUE TITLE
Implement dynamic search - Family Register list

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#11]
In the family register list (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/8), the dynamic search bar allows you to search for a family or a family member. Below are the search parameters:

- [x] {fam_name} from Family Registration form
- [x] {surname}, {first_name}, or {middle_name} of any family member in that family, including U5 children
- [x] {opensrp_id} of any family member in that family

Minimal viable feature search result: brings up the existing rows, regardless of what is searched is visible (so "David Smith Family" with child "Edward Smith".. if you search "Edward", then the "David Smith Family" would appear as normal)

The nice to have version that would work well for the TZ facility worker app: the matching term or ID appears in a new line. For example with the above scenario, the "David Smith Family" row would get an additional row of text that says "Under 5 child: **Edward** Smith". Or for example if a child ID were searched it'd be: if "2353" were searched it might add a row that said "Jake Smith: ID 898**2353**"

**Comment by faith-mutua** [comment]
QA 29 Jan:

- [ ] The nice to have version that has the matching term or ID appear in a new line is not working yet.

**Comment by cagulas** [comment]
I'll close this and move the nice to have feature into another issue.
