### ISSUE TITLE
Edit child registration form not populating some fields

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#111]
the following fields are not being populated in the form when you open it to edit it, even though they were answered in the original child registration form:

- Picture
- Middle name
- Breastfeeding
- Physically challenged

Also, if you hit the device back button, or back arrow, the confirm form close popup says that all data you have entered in this form will be cleared. We have another version of the confirmation that says all form changes made will be lost. We should use this version instead. You can get this from the OpenSRP Ona devs when you work on this.

**Comment by mahmud6390** [comment]
can not test with picture.Other option are fixed.

**Comment by cagulas** [comment]
Lgtm
