### ISSUE TITLE
Implement dynamic search - Child Register list

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#12]
In the child register list, the dynamic search bar allows you to search for a child record by the child's name or ID or the primary caregiver's name or ID. Below are the search parameters:

- [x] {surname}, {first_name}, or {middle_name} of the child or the child's primary caregiver
- [x] {opensrp_id} of the child or the child's primary caregiver.

**Comment by mahmud6390** [comment]
searching by child name,id. need to add by caregiver name and id

**Comment by mahmud6390** [comment]
@keymane need fts help for this issue.

**Comment by cagulas** [comment]
Lgtm
