### ISSUE TITLE
Final clean up on the Child register page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#122]
- [x] The caregiver's and child's names are now a bigger font size and they're getting cut off in the row. Can we use the same font size as what's in the family register right now?
- [x] The line that separates the demographic details from the visit button is not continuous. Let's match what's in the family register now

**Comment by cagulas** [comment]
15 Feb:

- [ ] Was the reduction in font size in the 15 Feb release? It's hard to tell. Let's reduce it further if it was. See below:

![screenshot_20190219-112858](https://user-images.githubusercontent.com/3488986/53000541-b4a4f300-3439-11e9-8bc2-fa83c98c4df3.png)

**Comment by mahmud6390** [comment]
@cagulas in previous we are using font size 16sp. But to using same font size as family register now using 19sp.May we revert it to 16sp?

**Comment by cagulas** [comment]
Hm, they may need to be different font sizes. The names are longer than the family name only.

@rowo what do you suggest?

**Comment by rowo** [comment]
Yes, if reducing font size is the only option I'd say go with that. ~22 characters is definitely too restrictive. 

Additional opportunities would be:
- Reduce width of button column and button text size
- Only show an initial of first or last name of caregiver
- Shorten age to 3 characters when appended to name

Here is a screenshot of the mockups vs. the screenshot, just for reference. Not sure if it's useful. 

![screen shot 2019-02-19 at 2 18 44 pm](https://user-images.githubusercontent.com/1584163/53041215-68fe4380-3451-11e9-8c97-67477df88a26.png)

**Comment by mahmud6390** [comment]
![device-2019-02-20-185659](https://user-images.githubusercontent.com/2793306/53093350-5f540900-3541-11e9-99d4-776796d6a2bc.png)
@cagulas  is it ok?

**Comment by cagulas** [comment]
@mahmud6390 Yea, think this looks ok.

@rowo want to take a quick look?

**Comment by rowo** [comment]
Yes, the text sizing matches the size in the mockup, which looks like a good size on my Nokia 6.1.

![untitled-1](https://user-images.githubusercontent.com/1584163/53104302-21cd8c80-34fd-11e9-89ec-380236672aa4.png)

**Comment by mahmud6390** [comment]
added in this pending PR https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/127

**Comment by cagulas** [comment]
Lgtm
