### ISSUE TITLE
Anchor the child's demographic details

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#123]
See screenshot below.

There is no need in this app to minimize the top portion, because we have at most 4 rows only. I think we should anchor the top demographic section and allow the bottom visit buttons and other rows to scroll if needed.

![screenshot_20190215-095425](https://user-images.githubusercontent.com/3488986/52839714-1b5ba100-3108-11e9-8472-99363a8a5947.png)

This is lower priority.

**Comment by mahmud6390** [comment]
Fixed pending PR https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/127

**Comment by mahmud6390** [comment]
![device-2019-02-22-010910](https://user-images.githubusercontent.com/2793306/53194913-ba1f5a80-363e-11e9-81e7-b57a12c429ff.png)
now top portion minimize remove. allow the scroll for bottom portion.
