### ISSUE TITLE
Remaining fixes to Add Child Under 5 form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#124]
- [x] Change "UNIQUE ID *" to just "ID *". See family head registration form.
- [x] ID field should not be editable. See the family head registration form.
- [x] Surname field and surname same as family name checkbox need some additional work. Let's implement exactly what's in the family head registration form. I.e. Surname should have an asterisk, as it's required, and the spacing between these fields should match what's in the family head registration form.
- [ ] When you enter an age, then tap on DOB unknown, then untap DOB unknown, the DOB is cleared, but the age in parentheses remains, which causes the question text label to overlap with it. Let's clear the age along with the DOB when the DOB unknown is selected.

**Comment by raihan-mpower** [comment]
@cagulas are we skipping the save enable disable feature on mandatory fields being filled up?

**Comment by cagulas** [comment]
@raihan-mpower Check what was done in the family registration form. I think @keymane can give more technical details. 

Just to be clear, this isn't required for the release we are trrying to get out today.

**Comment by cagulas** [comment]
Moving last issue to new issue and closing this.
