### ISSUE TITLE
Implement child monthly home visit schedule

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#13]
- [x] Due date is the first of the calendar month for all children in the list, i.e. Dec 1st, Jan 1st, etc. (see Bob Smith in the mockup for that button state)
- [x] If the visit is not done during the calendar month, the visit becomes red and overdue on the first of the next calendar month, i.e. if Bob Smith is not visited in December, on Jan 1st his button turns red (see child Eddie for this button status)
- [x] Note that for the red overdue status, we're also showing how many months ago the last visit was, i.e. "3 M"
- [x] When a child is visited, the button says "Visit done" (see first two children in the list). The button becomes due again (i.e. Bob Smith button) on the 1st of the next calendar month.
- [x] Visit not done is the status for when the CHW marks that she didn't visit the child that month - this button is available from the child's profile view (issue to be created). If they mark that the visit isn't done, the home visit will still become red and overdue on the 1st of the next month. So just because they "mute" the due button doesn't mean it won't be considered overdue the next month.
- [x] The Visit done and Visit not done buttons are not tappable.
- [x] The due and overdue buttons are tappable and take the user to the child's home visit form page (issue to be created).

<img width="404" alt="screen shot 2018-12-03 at 2 16 07 pm" src="https://user-images.githubusercontent.com/3488986/49370702-0923b680-f706-11e8-9a08-b005f38fdce4.png">

**Comment by mahmud6390** [comment]
visit status updated from visit data.

**Comment by faith-mutua** [comment]
QA 05 Feb

- [ ] Remove the space in between the text in the `RECORD HOME VISIT` button.

**Comment by cagulas** [comment]
Created a new issue for a bug, closing this.
