### ISSUE TITLE
Change the confirm home visit close popup

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#133]
When you hit the x button to exit a home visit without submitting it, the popup can be the same as the confirm form close popup.

**Comment by mahmud6390** [comment]
![exit_dialog](https://user-images.githubusercontent.com/2793306/53316310-9a638d00-38f1-11e9-8d7e-d57dd7ef2fe2.png)

**Comment by cagulas** [comment]
Lgtm
