### ISSUE TITLE
If you exit a service page, it shouldn't be shown as answered

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#135]
When you exit a service screen on the home visit, e.g. obs & illness episodes, it should still show the empty white circle status. This goes for any of the services on the page, but I'm noticing this for breastfeeding and obs & illness episodes specifically. Right now, if you exit the page without saving, it still shows the yellow check icon.

**Comment by mahmud6390** [comment]
fixed in pending PR #127

**Comment by cagulas** [comment]
Lgtm
