### ISSUE TITLE
Fix all the icons in the home visit

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#136]
After speaking with Eph, the icons seem to all be the right size, but they are showing up very blurry. See below. Let's fix these. 

![screenshot_20190219-122822](https://user-images.githubusercontent.com/3488986/53004316-f76ac900-3441-11e9-95a2-3178f202de05.png)

@rowo I can't find the screenshot in marvel anymore, but can you post here a good example of how big the icon should be on these screens. We used to have a mockup for this somewhere.

**Comment by mahmud6390** [comment]
added in this pending PR #127

**Comment by rowo** [comment]
@cagulas Here are some examples of how big the icons could be. I think depends on if there are additional questions to the form or only the one. The Yes and No radios seem a bit close together in that screenshot.

![artboard](https://user-images.githubusercontent.com/1584163/53047270-111b0900-3460-11e9-9695-cf5e8556e947.png)
![artboard copy](https://user-images.githubusercontent.com/1584163/53047271-111b0900-3460-11e9-8a97-3bbd3cf97f0f.png)

**Comment by mahmud6390** [comment]
![device-2019-02-20-182153](https://user-images.githubusercontent.com/2793306/53091637-a5f33480-353c-11e9-9910-1135fe11c240.png)
![device-2019-02-20-182214](https://user-images.githubusercontent.com/2793306/53091638-a5f33480-353c-11e9-9cfe-53609181d6ff.png)
is it ok?

**Comment by cagulas** [comment]
Yea looks good.

@rowo Want to take a quick look?

**Comment by rowo** [comment]
@mahmud6390 please:
- Use an upper limit for image size (use the MNP size, which on the screenshots that one is ~380 px vs. ~475 px for the breastfeeding)
- Use a consistent bottom margin (the MNP one is good)

**Comment by cagulas** [comment]
Screenshots shared on Slack look good, closing this.
