### ISSUE TITLE
Birth Cert and Obs & Illness episodes fixes

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#137]
15 Feb build:

Obs & Illness Episodes:
- [ ] Constraint on the date field needs to be fixed. Right now I'm forced to select today's date. It should be >= {dob} and <= {today} as per the data dictionary.
- [ ] We should show the answers that were inputted in the form back on the home visit page, similar to how the ANC app shows the test results on the Tests contact container: https://marvelapp.com/3aj9f30/screen/44144213

We can show:

Date                [date_of_illness]
Description    [illness_description]
Action taken  [action_taken]

Similarly, for the birth certification, can we show the same data inputs in the home visit page after you save your answers? 

We can show:

1) if kid has birth certificate, [birth_cert] = yes

Has birth certificate?    [birth_cert]
Issuance date                [birth_cert_issue_date]
Number                          [birth_cert_num]

2) if kid does not have birth certificate: [birth_cert] = no

Has birth certificate?       [birth_cert]
Birth notification done?   [birth_notification]

**Comment by mahmud6390** [comment]
ok.will be add to show in home visit screen. right now it's showing at medical history screen.

**Comment by cagulas** [comment]
Ok, thanks.

**Comment by mahmud6390** [comment]
![device-2019-02-24-125257](https://user-images.githubusercontent.com/2793306/53296121-35e1f880-3833-11e9-87ed-fbf9001fa81e.png)
@cagulas is it like this?

**Comment by mahmud6390** [comment]
![device-2019-02-24-160237](https://user-images.githubusercontent.com/2793306/53299421-fc75b100-3863-11e9-8b5d-a69af302da18.png)
@cagulas is it ok?

**Comment by cagulas** [comment]
Looking really good!

@rowo Do you think the font color should be flipped, so that the answers are in darker font? Or anything else you'd like to change here?

**Comment by rowo** [comment]
@cagulas Where can I see what is supposed to show up in the result subtext based on answers from the task? I want to see if the subtexts are being treated consistently since the ones shown above for Illness and Birth Certificate don't follow the pattern I expect.

**Comment by cagulas** [comment]
@rowo Sorry I'm having trouble sending screenshots now, but for immunizations and other services, you should be able to see how the info is displayed as sub-text in the Feb 15 app.  Birth cert. and Obs & Illness are the outliers here as it's a short series of questions instead of the service + date format of the others.

**Comment by rowo** [comment]
I will check out the app, thanks. It was showing some stuff that seemed off so I thought I'd ask.

The immunizations subtext doesn't follow a question-answer format (if it did, the immmunization subtext would be more like "immunizations done: xyz", "date immunizations done: dd/mm/yy", so I don't think "short series of questions" is a strong argument on why we couldn't do something more succinct or at least something that doesn't introduce a whole new style and display pattern.

As for if they are outliers — I don't think they are in terms of information captured. Immunizations easily could've followed the same "Did they receive X? Yes or No" series of questions as birth cert. Therefore the subtext, which presents the information captured, doesn't necessarily need to be different either.

**Comment by cagulas** [comment]
@rowo What do you suggest then? I'm happy to go along with anything you say.

**Comment by rowo** [comment]
In an earlier comment I asked "Could birth certification subtext be something like "Birth certificate issued DD/MM/YY (or whatever standard date format we're using)"? Is the birth certificate number shown because the user is expected to recheck the number from this screen rather than before saving that portion of the form?"

And for Observation and Illness, what do you think about something like "DD/MM/YY (or whatever standard date format we are using): description" then after  line break, "Action: managed/referred"

Then relatedly for MNP and breastfeeding type items, maybe repeating "MNP" isn't necessary because it's already the list item and just the dose or month is okay. For vaccines it's helpful since they are grouped.

**Comment by mahmud6390** [comment]
@rowo yeah after birth certification form data set this screen showing like as preview "Has birth certification:yes/no,if "yes" then show the value date and number if select as "no" then showing the "was the birth notification:yes/no

For Vitamin/MNP/Deworming.. first like showing like "Vitamin A 1st dost" and second like showing "provided on <date of service taken>" if user select as "Dose not given" then second like showing as"Not given"
For Observation and Illness,ok if i use like this date:description then action:managed/refered all are "black font" or any other view.it'll help me if you share any screen shot as mock up.

**Comment by rowo** [comment]
@mahmud6390 Here's a mock up of various possibilities:

<img src="https://user-images.githubusercontent.com/1584163/53498423-52b93e80-3a74-11e9-9ba6-28ab4cd33f3e.png" width="400px">

**Comment by mahmud6390** [comment]
![device-2019-02-28-133614](https://user-images.githubusercontent.com/2793306/53549549-a99b4280-3b5e-11e9-87a6-dc3b5cf8d6df.png)
![device-2019-02-28-133644](https://user-images.githubusercontent.com/2793306/53549550-aa33d900-3b5e-11e9-9056-2519adf345e4.png)
@cagulas is it ok now?

**Comment by cagulas** [comment]
Yes, looks great

**Comment by mahmud6390** [comment]
pending PR https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/173
