### ISSUE TITLE
Implement monthly home visit schedules on the family register page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#14]
For the Liberia app, the only monthly home visit schedule will be that of the child home visit (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/13), but there may be multiple children in the same family, so the home visit buttons on the family register list (see below) are based on the "most due" service. E.g. if there are two children in the family, Jack and Jill, and Jack's home visit was completed in December, but for whatever reason, Jill's home visit was not completed, the visit due button on the family register list would still show the blue visit due button state on account of Jill. 

So, that means visit done status is only shown if every child in the family was visited that month. And visit not done status is only shown if every child in the family is marked as visit not done. I.e. if one child is due and another child was marked as not done, then the overall status is still due.

So, essentially, the order is:
**Overdue, then due, with visit done and visit not done statuses only shown if EVERY child in the family is marked that way.**

Tapping on the blue or red button opens the family profile page and lands on the "Due" tab.

In future, there will be additional types of visits, i.e. ANC visit, HIV follow-up visit, etc., so this needs to be taken into account as well, but for now, we're just doing the monthly child home visits.

<img width="369" alt="screen shot 2018-12-03 at 2 41 47 pm" src="https://user-images.githubusercontent.com/3488986/49371764-9a485c80-f709-11e8-99ec-4dea4b482a0b.png">

**Comment by faith-mutua** [comment]
QA 04 Feb:

- [ ] Tapping on the blue or red button doesn't open the "Due" tab of the family profile page. The buttons are unresponsive.

**Comment by mlberg** [comment]
You have to click on the name part of the row.  I noticed this too.  It probably makes sense to have the buttons clickable

**Comment by cagulas** [comment]
@rkodev what's the best way for me to test this. The first visit is working correctly, but to test future schedules, should I change the device date and time to test that it correctly becomes due in the future?

**Comment by rkodev** [comment]
@cagulas yes changing the device date to a future date should allow you to record a visit. (Although sync will fail).

**Comment by cagulas** [comment]
Lgtm
