### ISSUE TITLE
Change Measles 1 and 2 to MCV 1 and MCV 2

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#146]
![screenshot_20190219-154842](https://user-images.githubusercontent.com/3488986/53016264-40307b00-345e-11e9-8b69-0d5ed3cede23.png)

**Comment by mahmud6390** [comment]
![issue_146](https://user-images.githubusercontent.com/2793306/53692713-ca61d300-3dbe-11e9-9f78-be996f9d6066.png)
text changes

**Comment by cagulas** [comment]
@mahmud6390 Looks good, can you just please double-check that there isn't an extra space between 1 and upcoming?

**Comment by cagulas** [comment]
closing this for now. It was taking Mahmud too long to find the cause of the extra space, so it's not something we'll address.
