### ISSUE TITLE
Remaining UI issues for Child's Home Visit page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#148]
Feb 15th build:

- [x] Let's increase the boldness of the SUBMIT button. Maybe this should be medium font?
- [x] I'm just noticing this, but the lines separating the rows appear different. For e.g. it looks like two superimposed lines are separating the breastfeeding from the Obs & Illness episodes rows
- [x] The month needs to be capitalized in "Due 25 dec 2018" for immunizations
- [x] Remove the space in the age for immunizations. E.g. it should be (6w) and not (6 w), (10w) not (10 w), (9m) not (9 m), etc.

**Comment by mahmud6390** [comment]
![device-2019-02-25-171249](https://user-images.githubusercontent.com/2793306/53333645-a9adff00-3920-11e9-8f0d-6352069c440b.png)
@cagulas it's looking like this.
    * "Due 25 dec 2018" it was hard coded text.Before loading the actual data this text was visiable so will be remove the text.

**Comment by cagulas** [comment]
@mahmud6390 Cool. Just to confirm, this only becomes bold/highlighted when all required services are answered in the home visit, right? Before the required fields are all answered, it should not be bold, but it should be the same font weight.

**Comment by mahmud6390** [comment]
@cagulas yeah that implementation as same as before.

**Comment by cagulas** [comment]
Lgtm
