### ISSUE TITLE
Remaining UI issues for the Child's Home Visit page when services are recorded

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#149]
Feb 15th build:

- [x] When you record immunizations are done or not done, there is an interpunct that is added at the end that needs to be removed. E.g. "BCG, OPV 0 provided on 17 Feb 2019 ·" and also "BCG, OPV 0 not given ·" I think this is added for when there are multiple results to record, but we need to remove this when there's a single result recorded only.
- [x] Add an "s" to "month" in "Exclusive breastfeeding [number] month"
- [x] For Exclusive breastfeeding, not sure where the "provided" came from. This isn't a good word to use in this context, since it's not a service provided. The top line should read "Exclusive breastfeeding [number] months" and the line below should read "No" or "Yes". It's not necessary to show the date here, as it's not a service. 
- [x] Check the color of the icon for exclusive breastfeeding, if they answer No to the question, that means they are exclusively breastfeeding, so the home visit page should say "Yes" and have a green check. If they answer Yes to the question, that means they are not exclusively breastfeeding, so the home visit page should say "No" and have a yellow check. Make sure "No" and "Yes" are capitalized.

**Comment by keymane** [comment]
@cagulas Regarding 
>     Add an "s" to "month" in "Exclusive breastfeeding [number] month"
Will the label show months even when the number is 0 and 1? 

![0months](https://user-images.githubusercontent.com/13656416/53234060-c25bb200-369f-11e9-8be9-f7808bab34d1.png)

**Comment by cagulas** [comment]
@keymane yes, that's fine. I don't think it's worth it to change it to "month" only for "1 month". Since "months" fits everything except 1, I think it's better to always keep it plural

**Comment by cagulas** [comment]
Lgtm
