### ISSUE TITLE
Fix issues with child service schedules

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#150]
Feb 15th build:

- [x] For some reason all birth immunizations are showing as due on 25 Dec 2018. Something might have broken here.
- [x] Check the overdue date for the exclusive breastfeeding service. It should be 2 weeks after due date. Pls re-check the service schedules spreadsheet for this. Right now I register a child born today and exclusive breastfeeding is showing as overdue.
- [x] Birth certification due date should be DOB + 12 months. I think it's becoming due right at birth. Pls consult the service schedule spreadsheet.

**Comment by mahmud6390** [comment]
![device-2019-02-27-155324](https://user-images.githubusercontent.com/2793306/53481702-f4a64e80-3aa7-11e9-8f76-714056f670dc.png)
@cagulas now birth certification,service overdue calculation based on spreadsheet.

**Comment by mahmud6390** [comment]
added in pending PR https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/165

**Comment by cagulas** [comment]
Closing. Lgtm
