### ISSUE TITLE
[discussion] Observation and Illness re-evaluation

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-unicef-wcaro#156]
## @cagulas brought up two issues
1. showing a green check for a sick child (Observation and Illness) seems counterintuitive
2. stuff like birth certificate and observation and illness are actually optional so you can submit without answering those

## Home visit checklist summary

These checkmarks are only showing whether the task were completed successfully. For vaccines that just means whether they were done or not by another party.

- Green - recorded as done successfully
- Yellow - recorded done partially or not done - Tapping and cancelling does not mean yellow (This seems like a bug in how it works in the Feb 15 APK). Yellow is “Saving” with a “No” option.
- Blank - no answer recorded

## No. 1 The difference with Observation and Illness

Observation and illness is different from vaccines in that the CHW has a job to do — but if they did their job correctly, they would've managed or referred (Row 90 in the child home visit data dictionary), so I suggest that outcome be included in the line under Observation and Illness. This isn't a change in approach from vaccine, but more of an understanding of what a check means in the check list. Here, a green check makes a lot of sense since the CHW completed his/her task. If there was an option of "did nothing" then it might show up as yellow.

![screen shot 2019-02-22 at 1 46 53 pm](https://user-images.githubusercontent.com/1584163/53263773-592c6c80-36a8-11e9-884c-eccfe1dfdc1a.png)

## No. 2 Observation and Illness and Birth Certificate are optional

I don't remember if it was finalized when the screens were created whether we'd make a user provide an answer for every bullet, which would make every check item required (for example, by answering yes or no for whether child is ill). The data dictionary is unclear to me since Obs and Illness seems like it's a required question and there is no  "yes" or "no" question for if the child is ill.

However, if we want to truly make them optional, I thin w can just add that bit to the labels:

<img src="https://user-images.githubusercontent.com/1584163/53263619-f3d87b80-36a7-11e9-8274-4bebec150308.png" width="350">

**Comment by cagulas** [comment]
@rowo Ok, thanks for this input.

- Birth certificate is actually required each time, so it's only the Obs & Illness Episodes that is optional. I like the suggestion to show optional as text next to it. I'll create a separate issue for this.

- https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/135 - Yellow check mark showing incorrectly should be fixed already.
