### ISSUE TITLE
Add optional text to obs & illness in home visit

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#157]
<img width="444" alt="screen shot 2019-02-25 at 8 52 39 am" src="https://user-images.githubusercontent.com/3488986/53317075-55346080-38db-11e9-97e8-c74febeba0c6.png">

We can add optional text to the obs & illness episodes in the home visit, as it's the only field that is optional before submitting the form.

**Comment by mahmud6390** [comment]
![device-2019-02-25-123126](https://user-images.githubusercontent.com/2793306/53318430-668c6580-38f9-11e9-81c7-1b5ea9ddf52d.png)

**Comment by cagulas** [comment]
Lgtm
