### ISSUE TITLE
Save button on vaccine widget should not be tappable if disabled

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#167]
In the 28 Feb release, we disabled the Save button on the immunization widget if all vaccines are unchecked, but one is still able to tap on it and the widget closes and the vaccines are marked as not given. 

If it's disabled, it shouldn't be tappable.

**Comment by mahmud6390** [comment]
@cagulas ok so if user unchecked all vaccine can't press "save" button but can be press at "vaccine not done" button right?

**Comment by cagulas** [comment]
Correct!

**Comment by mahmud6390** [comment]
pending PR https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/174

**Comment by cagulas** [comment]
Lgtm
