### ISSUE TITLE
Fix date constraint on Obs & Illness episodes

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#171]
Obs & Illness Episodes:

Constraint on the date field needs to be fixed. Right now I'm forced to select today's date. It should be >= {dob} and <= {today} as per the data dictionary.

**Comment by mahmud6390** [comment]
@cagulas i can't reproduce the issue. would you please mention the date of birth of the child?

**Comment by cagulas** [comment]
@mahmud6390 This should be replicable for any child. Go to home visit and open the observation and illness widget and try to select a date that's not today's date.

**Comment by mahmud6390** [comment]
[issue-171.mp4.tar.gz](https://github.com/OpenSRP/opensrp-unicef-wcaro/files/2924487/issue-171.mp4.tar.gz)
@cagulas it's showing little bit strange.i am getting like this.

**Comment by cagulas** [comment]
This is done. Will be included in the next release.
