### ISSUE TITLE
Implement child age label categories

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#18]
Same as ZEIR:

From age 0 days to 13 days - In days
From age 14 days to 13 weeks, 6 days - In weeks and days
From age 14 weeks to 51 weeks, 6 days - In months and weeks
From age 1 year - In years and months

**Comment by cagulas** [comment]
@rowo I'm sorry I don't understand your comment above at all. What's the "truncate to first grouping mean"?

This isn't just for identification purposes; showing the more detailed age also helps to determine where they are in their service schedules.

Can we please not make anymore changes? I think this is fine as is.

**Comment by rowo** [comment]
@cagulas Meaning when we list a name on a row, it goes "Ed Baker, 33". Truncating means it wouldn't say "Sally Baker, 3m 15w" and would say "Sally Baker, 3m". It's a much quicker read when you have a list of people.

**Comment by cagulas** [comment]
@rowo Ok, thanks. I see your point about being a much quicker read. Maybe we can revert to this and decide after the first releases are out of the way.

**Comment by rowo** [comment]
@cagulas Ok up to you I know timing wise this is a bit late. We can keep the format as is and see how it goes if that's best for the project.

**Comment by rowo** [comment]
@cagulas Cool I know it's not great timing. We can do whatever is best for the project and change later when we have the foundations built if that is better.

**Comment by cagulas** [comment]
Lgtm
