### ISSUE TITLE
There should not be an option for Child DOB unknown

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#183]
Just noticing now that unlike the family head and family member registration forms, in the child registration form, there should not be an option for checking DOB unknown.

We can hide this from the form hopefully instead of removing it?

**Comment by mahmud6390** [comment]
![dob unknown](https://user-images.githubusercontent.com/2793306/53861711-2de23f80-400f-11e9-97d9-b0d2a09d933f.png)
and edit form
![dob unkown](https://user-images.githubusercontent.com/2793306/53861733-3c305b80-400f-11e9-9fc3-71d26f1413e3.png)

**Comment by mahmud6390** [comment]
@cagulas second image is edit form.do we need to change the title of this form as "Edit child under 5"

**Comment by cagulas** [comment]
Yes, if that's a simple thing to change, please do. I've also listed the issues here: https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/128

**Comment by cagulas** [comment]
Closing this issue for now.
