### ISSUE TITLE
Implement Family Registration form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#19]
- [x] The family reg form can be accessed from the Add Family button in the bottom navigation bar of the app.
- [x] The form is bifurcated into: "Family Details" and "Family Head" sections (see below), similar to how the new ANC forms work
- [x] Please follow the exact content in the data dictionary, "Family Registration" tab, for this form (https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=160516215).
- [x] Please note instead of the back arrow it should show an X in the top left of the family head section.
- [x] Once all required fields are answered at a minimum, the form SAVE button becomes active. Please note that the SAVE button should be available on both the family details or the family head section, but regardless where they press the save button, it can only be saved if all required fields are answered.
- [x] If they exit the form without saving, there should be a confirmation message saying that all information they entered will be lost. There is no in progress state.
- [x] Once the family is registered, they appear at the top of the list in the families register page.
- [x] As discussed with @keymane, once the family head is registered, they no longer have to be associated with the family details; we are actually going to split the form for the purposes of later edits, i.e. family registration details are edited separately from the family head details. This is done, because the role of family head can actually change between members.
- [x] Also note that the family head automatically becomes the primary caregiver, since s/he is the first person registered in the family, but this role can be transferred to another family member when they are registered.

<img width="406" alt="screen shot 2018-12-03 at 3 16 25 pm" src="https://user-images.githubusercontent.com/3488986/49373294-a387f800-f70e-11e8-9c46-9bd0dc39071c.png">

<img width="371" alt="screen shot 2018-12-03 at 3 18 13 pm" src="https://user-images.githubusercontent.com/3488986/49373302-aaaf0600-f70e-11e8-8dd8-34c002677d41.png">

**Comment by cagulas** [comment]
@keymane If it's more difficult to implement to have it on both pages, then that's fine I think. I do think it's more user-friendly to have it on both, because they can always go back to check their answers on the first page. If it's the same level of effort, I would say do on both pages; otherwise, last page is fine. The save button won't become active anyway until all required fields are answered.

**Comment by keymane** [comment]
Yes it's more effort to add it in all the pages but the next button and icon validates the form, that is, checks if all the required fields have been set in that page.

**Comment by cagulas** [comment]
Copy-pasting all unfinished QA into this issue, as checked in the 6th Feb release:

- [ ] Can we not have the required questions be required until you try to submit the form? Right now I can't go to the family head page until all questions on family details are answered. Speak with the ANC team, as this is functionality that's implemented in WHO ANC app.
- [ ] When you select a longer income, e.g. communication, social, and personal services, the answer bleeds into the GPS coordinates. Let's add some padding to this type of question.
- [ ] See all the fields highlighted in bright pink in the data dictionary that don't seem to be implemented correctly. @rkodev I called your attention to these in the comments.

**Comment by keymane** [comment]
_Can we not have the required questions be required until you try to submit the form? Right now I can't go to the family head page until all questions on family details are answered_

@cagulas  This will be a bit tricky to implement now. We can disable the required fields and the user can navigate to the second page but what happens when they submit the form on the second page and some required fields have not been filled in the first page? 

The native form library has been implemented as form wizard meaning each step is validated and we don't have the feature of navigating to a "previous" page that failed validation when the form is submitted in the last page. For ANC they just disabled the required fields and retrieved them out of the form

**Comment by keymane** [comment]
@cagulas Yes, we can remove the required error message popup immediately and have them shown when the user clicks `Next` in the form. 

For ANC the logic for getting the required fields is done outside the form, in the container and finalize pages.

**Comment by cagulas** [comment]
@keymane Ok, between the two options, I think it's better to not show the required error messages for the fields immediately. Thanks for explaining the situation.

**Comment by cagulas** [comment]
Lgtm
