### ISSUE TITLE
Implement Family Profile page - Members tab

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#21]
Marvel: https://marvelapp.com/9j1277a/screen/48411529

<img width="376" alt="screen shot 2018-12-05 at 11 23 33 pm" src="https://user-images.githubusercontent.com/1584163/49561347-cff56d00-f8e4-11e8-81c8-e7fbfae256e0.png">

- [x] This is the page you land on when you tap on a family record row in the family register list
- [x] Return to all families goes back to family register list 
- [x] {fam_name} Family, then {village_town} from Family Registration form
- [x] Members, Due, Activity tabs
- [x] Due tab shows number of due items in parentheses
- [x] Similar to ANC, you can tap or swipe between the tabs
- [x] Members tab lists all family members, from oldest to youngest, followed by any deceased members
- [x] Deceased members are shown at the bottom of the list, in lighter grey, italic font (see mockup)
- [x] For deceased members, if they previously had a profile picture, remove the picture and switch back to the avatar
- [x] Age shown for the deceased is the age at which they died
- [x] For each member, show their {first_name} {middle_name} {last_name} followed by age and sex
- [x] The head of family and primary caregiver statuses are shown below, if applicable.
- [x] For all living family members, the right arrow takes you to the member's profile page
- [x] The blue dot next to Bob Smith indicates that he has a user-related task due such as a home visit (not just a general health service due such as Penta 1). This dot can be blue or red, depending on if the task is due or overdue, respectively.
- [x] I'm creating a separate issue for the floating action button (TBD)

~~@rowo For that second to last point, for children, is this counting only home visits or individual services? I.e. if they have a home visit due, it's blue, but what if they don't have a home visit due but they have services, i.e. Penta 1 due? I'm inclined to say it's only about the home visits. What do you think?~~ RW: I updated the point.

**Comment by cagulas** [comment]
QA 7 Feb release:

- [ ] The family icon at the top next to family name is blurry. Replace with an SVG image if needed.
- [ ] Family location field {village_town} is not populating underneath family name.
- [ ] Due tab shows number of due items in parentheses (not implemented yet)
- [ ] I think the primary caregiver action broke. When I register a new family and family head, the family head should automatically be the primary caregiver, but it's now showing only family head status.
- [ ] Deceased members are shown at the bottom of the list, in lighter grey, italic font (see mockup) **CG: I don't think this was implemented. It's not happening. I just marked a member of the Totty family as deceased, and they disappeared from the member list instead of appearing at the bottom as deceased**
- [ ] For deceased members, if they previously had a profile picture, remove the picture and switch back to the avatar
- [ ] Age shown for the deceased is the age at which they died
- [ ] The blue dot next to Bob Smith indicates that he has a user-related task due such as a home visit (not just a general health service due such as Penta 1). This dot can be blue or red, depending on if the task is due or overdue, respectively. **CG: Not implemented yet**

**Comment by mlberg** [comment]
Could this be post QA release?  Eg not by Thursday

**Comment by rkodev** [comment]
@mlberg this issue is already working on the development branch.

**Comment by cagulas** [comment]
Lgtm
