### ISSUE TITLE
Implement Family Profile page - Activity tab

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#24]
Clickable prototype: https://marvelapp.com/9j1277a/screen/49183725

<img width="372" alt="screen shot 2018-12-06 at 3 41 46 pm" src="https://user-images.githubusercontent.com/1584163/49610760-7d13c800-f96d-11e8-84c6-e9e1f68a082d.png">

- [x] The Activity tab shows a reverse-chronological list of all home visits for all children of that family.
- [x] As the list gets longer, it scrolls. In the future, we might need pagination or infinite scroll progressive loading.
- [x] Visits that are completed show up as activity list items with label row 1 "`first name` `middle name` `last name`, `age` · `form name`" and row 2 "Completed on `completion date`"
- [x] Visits marked as not done show up as activity list items with label row 1 "`first name` `middle name` `last name`, `age`· <form name>" and row 2 "Marked not visited on `marked visit not done date`"
- [x] The thing between name and form name is an interpunct or middle dot. A comma is okay if you want to be less fancy.

**Comment by rowo** [comment]
@cagulas responded above

**Comment by cagulas** [comment]
@rowo Ok great, this sounds good to me. Thanks.

**Comment by rowo** [comment]
@cagulas Is this not done status still applicable? I know we talked about it, don't remember what we decided on.

**Comment by cagulas** [comment]
@rowo Thanks for updating the issue. Yes, it's still applicable.

**Comment by faith-mutua** [comment]
QA 05 Feb

- [ ] Form name is not shown in row 1 together with `first name` `middle name` `last name`, `age`

**Comment by cagulas** [comment]
Lgtm. We'll have to address the issue of the line getting cut off eventually, but this is good for now.
