### ISSUE TITLE
Implement Call widget

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#25]
<img width="386" alt="screen shot 2018-12-03 at 8 50 09 pm" src="https://user-images.githubusercontent.com/3488986/49391621-3dff3000-f73d-11e8-9a70-c1faacf45c0c.png">

- [x] The call widget is opened from the floating action icon on either the family profile page or the child's profile page
- [x] Clicking outside the box or the top right X takes you back to the page you were on
- [x] At most two names are listed, if the family head and primary caregiver are separate family members, but if it's one person, list "family head" and "primary caregiver" roles underneath the same name.
- [x] Put the person's first name, middle name, last name
- [x] "Call {phone_number}" where phone number variable comes from either the family registration form or the family member registration form
- [x] Tapping on the above launches the phone's phone app with the number populated in the dialer.

**Comment by rkodev** [comment]
Update the call action to read stored data. Works from the child module FAB and the family module FAB.

**Comment by cagulas** [comment]
QA 21 Jan:

- [ ] Right now the phone number is just copied to clip board instead of opening up the phone dialer app. It should open up the phone dialer app with the number pasted in.
- [ ] the top right X button doesn't need to be so big. We can reduce the font size a bit and make it medium instead of bold font. We can also reduce the right margin of the X button ever so slightly.
- [ ] Remove the space after head of family and before the comma
- [ ] The phone number shouldn't have the brackets around it. 
- [ ] Don't capitalize "Family" in "Head of family"

**Comment by rkodev** [comment]
Added a dialog to display the phone number when the phone number is missing

**Comment by faith-mutua** [comment]
QA 29 Jan:

Looks good to me

**Comment by cagulas** [comment]
@rkodev So for Faith's J5 phone, the phone widget was launched, but on my J5, it continues to just say the phone number was copied to clipboard and doesn't launch the phone app. Any idea why or what I need to do differently?

**Comment by rkodev** [comment]
@cagulas when a phone doesn't not have a calling capabilities, it copies the number to a clipboard , notifies the user and also open a small popup middle of the screen. Please check if the phone / tablet can call. Otherwise it should open the phone dial pad

**Comment by cagulas** [comment]
@rkodev Ah, that's it. This phone doesn't have a SIM in it anymore. That must be why. Cool, I'll close this again.
