### ISSUE TITLE
Implement Family details edit action

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#26]
From the floating action icon on a family profile page, this options allows the user to re-open the family details section of the family registration form. They can edit any field marked as editable in the data dictionary.

Note, we are splitting the form from the family head registration form, so that for editing purposes, they are accessed separately.

**Comment by faith-mutua** [comment]
QA 29-Jan

- [ ] Family details are not being updated after editing.

**Comment by faith-mutua** [comment]
QA 04-Feb:

Lgtm

**Comment by cagulas** [comment]
QA 7 Feb release:

- [ ] We can decrease the space between the back arrow and the form title a little bit.
- [ ] Please change the popup when you hit the back arrow or back button to the version where it says all changes you have made will be lost. You can get this version from the ANC app.
- [ ] Village/Town is not getting populated.

**Comment by rkodev** [comment]
@cagulas should all the forms have the same popup when using the back button or only this specific form?

**Comment by cagulas** [comment]
@rkodev If it's a blank form they've opened, then the message should be that all data entered will be lost, but if they are opening an existing form to make edits, then the message should say that any changes made will be lost.

**Comment by cagulas** [comment]
Lgtm
