### ISSUE TITLE
Implement Add Family Member action

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#27]
From the floating action button on the family profile page, the "Add new family member" option opens this widget:

<img width="379" alt="screen shot 2018-12-03 at 9 03 44 pm" src="https://user-images.githubusercontent.com/3488986/49392237-f11c5900-f73e-11e8-890c-83cb49e9cb4d.png">

- [x] X button takes you back to family profile page
- [x] Two options are shown - Child under 5 years and Other family member. Tapping on these rows launches the registration form for that type of person (separate issues to be created)

**Comment by cagulas** [comment]
@keymane What do you think. Whatever makes the most sense for splitting up the work works for me. We can also discuss today on the call in a few minutes.

**Comment by cagulas** [comment]
QA 21 Jan:

Looking much better overall!

- [ ] Let's make the X button the same font boldness as the title. Right now, I think it's a little more bold than "Add family member"
- [ ] Sorry I forgot to mention this earlier, but let's add a "do" to the question, so it reads "What kind of family member do you want to add?"

**Comment by cagulas** [comment]
@raihan-mpower Just making sure you saw the above QA from almost 3 weeks ago.

**Comment by raihan-mpower** [comment]
@cagulas the X is an icon, but ill try to see what i can do, i think i missed out the last comment , on it right away

**Comment by cagulas** [comment]
@raihan-mpower great, thanks!

**Comment by cagulas** [comment]
Lgtm!
