### ISSUE TITLE
Implement Remove Family Member action

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#28]
Marvel link: https://marvelapp.com/9j1277a/screen/49183723

<img width="378" alt="screen shot 2018-12-05 at 10 15 57 pm" src="https://user-images.githubusercontent.com/1584163/49559069-60c74b00-f8db-11e8-8c26-3397f27e333a.png">

- [x] Tapping on the Remove existing family member button in the floating action icon in the family profile page opens this screen (https://marvelapp.com/9j1277a/screen/48411529)
- [x] All family members are listed, from oldest to youngest (i.e. mockup is not the correct order)
- [x] Family head and primary caregiver roles are displayed below the member, as shown above. The two roles can be the same person or different people.
- [x] First name, middle name, last name, and age are shown on the first line, then gender is shown on the second line
- [x] Tapping the right arrow launches the remove member form for that family member (issues to be created)
- [x] The remove entire family option shows number of adults and number of children in the family
- [x] If an entire family is removed, all family member records are automatically archived as well; otherwise, if just a single family member is removed, only that member is archived, and the family record remains
- [x] If you select the family head or primary caregiver family member, before you can remove that person you first need to select a new family head and/or primary caregiver (issues to be created)
- [x] Quick note on displaying age. For children's ages, I created an issue on this (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/18), so for displaying ages above for children, use "d" for days, "w" for weeks, "m" for months, and "y" for years. For adults (not U5 child), just show the number, you don't have to show the years.

**Comment by faith-mutua** [comment]
QA 29 Jan:

- [ ] Tapping the right arrow does not launch the remove member form for that family member. This only works for the `Remove entire family` option.

**Comment by rkodev** [comment]
Resolved

**Comment by faith-mutua** [comment]
QA 05 Feb

- [ ] Not all images for the family members are shown even though they were captured when registering them. The only image that's displayed is for the second family member.

**Comment by cagulas** [comment]
Lgtm
