### ISSUE TITLE
Implement Change Family Head action

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#30]
<img width="368" alt="screen shot 2018-12-04 at 9 37 11 am" src="https://user-images.githubusercontent.com/3488986/49423372-55bfce00-f7a8-11e8-8d25-5ecb9c4c70bb.png">

<img width="336" alt="screen shot 2018-12-07 at 9 40 19 am" src="https://user-images.githubusercontent.com/3488986/49631727-286f5c00-fa04-11e8-9dc3-0b858c8685e3.png">

- [x] The change family head option in the floating action button on the family profile page opens this full screen dialog
- [x] Only eligible family members are listed here, meaning only adults (so U5 children are not shown in the list), and the current family head isn't shown either. If there are no eligible members, then the list will be blank, which is fine for now.
- [x] For family heads and primary caregivers, a phone number is required, while other phone number and education level are optional, so if a new family head or primary caregiver is selected, where this information is blank, we show these 3 questions (see 2nd mockup above for an idea of this, but follow the data dictionary, phone_number, other_phone_number, and highest_edu_level fields.

**Comment by faith-mutua** [comment]
QA 29 Jan: 

- [ ] When changing back to the previous family head, their phone number is not displayed under the second question. It's only displayed if a user selects the option **No**

**Comment by rkodev** [comment]
Resolved. The number was being cut off today.

**Comment by faith-mutua** [comment]
QA 05 Feb

lgtm

**Comment by cagulas** [comment]
QA 7 Feb:

- [ ] Please implement the same improvements as listed in QA for https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/31.

**Comment by rkodev** [comment]
completed

**Comment by cagulas** [comment]
Closing and moving all remaining QA to new issue.
