### ISSUE TITLE
Implement Change Primary Caregiver action

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#31]
No mockup provided for this. See https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/30 for guidance.

- [x] The change primary caregiver option in the floating action button on the family profile page opens this full screen dialog.
- [x] Only eligible family members are listed here, meaning only adults (so U5 children are not shown in the list), and the current primary caregiver isn't shown either. If there are no eligible members, then the list will be blank, which is fine for now.
- [x] For family heads and primary caregivers, a phone number is required, while other phone number and education level are optional, so if a new family head or primary caregiver is selected, where this information is blank, we show these 3 questions (see 2nd mockup above for an idea of this, but follow the data dictionary, phone_number, other_phone_number, and highest_edu_level fields.

**Comment by faith-mutua** [comment]
QA 29 Jan

- [ ] When changing back to the previous family head, their phone number is not displayed under the second question. It's only displayed if a user selects the option **No**

**Comment by rkodev** [comment]
QA 29 Jan - Resolved

**Comment by faith-mutua** [comment]
QA 05 Feb

- [ ] The text `Change primary caregiver` overlaps the `Save` button.

**Comment by rkodev** [comment]
Resolved

**Comment by cagulas** [comment]
QA 7 Feb release:

- [ ] Caregiver should be one word in the form title and in the question label
- [ ] Form title shouldn't be bold font. Should be same font as X button
- [ ] Save should be all caps and not bold font. See mockup for change family head.
- [ ] Person's age is missing
- [ ] Let's make the person's name and age slightly darker font than the gender. See https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/30 for guidance on all of this.
- [ ] I actually don't think we need to ask if her phone number is the same. We can just display the phone number field, and if a phone number for them already exists, we can have it populated in the field and they can edit it if required. So we only need to show the 3 fields from the form, i.e.:

Phone number
Other phone number
Highest education level

**Comment by rkodev** [comment]
completed

**Comment by cagulas** [comment]
Closing and moving all qa to new issue.
