### ISSUE TITLE
Implement change family head/primary caregiver widgets if trying to remove family head/primary caregiver member

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#32]
When removing a family member (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/28), the user might select the family head or primary caregiver to remove. Before the family head or primary caregiver can be removed, the user must first select a new family head/primary caregiver.

- [x] The below widgets show up when the user selects the family head or primary caregiver to remove (if the same person is both family head and primary caregiver, these screens show up subsequently, i.e. press save on family head widget and primary caregiver widget pops up immediately.

<img width="390" alt="screen shot 2018-12-04 at 9 34 03 am" src="https://user-images.githubusercontent.com/3488986/49424009-55283700-f7aa-11e8-9c49-8f7d9eb17622.png">
<img width="364" alt="screen shot 2018-12-04 at 9 34 23 am" src="https://user-images.githubusercontent.com/3488986/49424012-56596400-f7aa-11e8-9c4d-5a8ab99d5ccc.png">

- [x] If the above is too difficult to implement, we can also go with the full screen dialogs (i.e. https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/30 and https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/31)
- [x] Not shown in the mockup, but please use the new way to display ages, i.e. name and age are in first line, then gender is on the second line.

**Comment by faith-mutua** [comment]
QA 29 Jan:

- [ ] Testing this on Samsung J5, the text is truncated at select.

**Comment by rkodev** [comment]
Resolved

**Comment by cagulas** [comment]
QA 7 Feb release:

- [ ] Let's make cancel and save buttons as all caps and the blue font that you see in the other data entry forms.
- [ ] Pls see the QA fo the change family head and primary caregiver actions and implement that here as well.

**Comment by rkodev** [comment]
@cagulas for the save and cancel buttons, should both be in blue font? or blue and light grey as in the mock up above

**Comment by cagulas** [comment]
@rkodev Ok cool, thanks for asking. In the above mockup, I think Save button is in grey font because it's disabled until all required fields are answered in the popup. My understanding is that it's hard for us to implement this Save button dynamic state, which is fine, so we should have both in the same blue font.

**Comment by cagulas** [comment]
will create a new QA issue for this.
