### ISSUE TITLE
Implement Add Child Under 5 form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#34]
No mockup provided for this, but it will be a similar-looking form to: https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/33.

Please use the exact content from the [data dictionary](https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=249843981), "Add Child Under 5" tab.

**Comment by cagulas** [comment]
QA 4 January:

- [ ] Pls see bright pink cells highlighted in data dictionary. These are the cells that were missed I think.
- [ ] Last 3 fields in the form get cut off when you enter the answer.
- [ ] When you submit the form, you should be directed back to the Members page. Right now, you land on the add family member widget.

**Comment by cagulas** [comment]
@mahmud6390 Also, I think something broke, and the child's last name is getting picked from the family head's first name. We need to make sure if you select that the surname is same as family name, then you pick the fam_name from the Family Registration form.

**Comment by raihan-mpower** [comment]
@cagulas is this how it is supposed to work
https://drive.google.com/file/d/1FdAoh6imsITBcC-yCzZ1W0qIM-4cw_ID/view?usp=sharing

**Comment by cagulas** [comment]
@raihan-mpower Yes, that's correct. Thanks.

**Comment by cagulas** [comment]
Putting all remaining issues into: https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/124
