### ISSUE TITLE
Add Remove Child Under 5 form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#35]
- [x]  The Remove Child Under 5 form is available from either the floating action button on the child's individual profile page, OR from the family profile page, "Remove existing family member" option, then select the child in the screen.
- [x] Follow the content in the [data dictionary](https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=1085543306), "Remove Child Under 5" tab. This should also be the name of the form.
- [x] After hitting the Save button, a separate popup widget appears to confirm the child's record should be removed (separate issue to be created)
- [x] Once the child's record is removed, it should disappear from the children register list.
- [x] If the removal reason is that the child died, then the record is still removed, but the child still appears in the family profile view. See https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/21 for more info. The child's profile picture should be removed, and the age at death (auto-calculated in this form) should be displayed. Refer to https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/18 for the displaying of the child age cutoffs.

<img width="367" alt="screen shot 2018-12-05 at 11 42 54 am" src="https://user-images.githubusercontent.com/3488986/49501180-54af9f00-f883-11e8-993e-68fe4336ce62.png">

- [x] In the above mockup, the back arrow (or tapping the device back button) takes the user back to the screen they were on before opening the form.
- [x] The SAVE button only becomes highlighted and tappable after all of the required fields in the form are answered.
- [x] Instead of "Remove Child", use "Remove Child Under 5" as the form title at the top.

**Comment by cagulas** [comment]
QA 21 Jan:

- [ ] This isn't hooked up yet in the child profile view. I can only open this form from the family members floating action icon.
- [ ] We have to reduce the font size for the form title. On my 5 inch smartphone, the form title is getting cut off by the SAVE button. Let me know if we need to truncate the name of the form to just "Remove U5 Child"
- [ ] The SAVE button should be not active and greyed out until all required fields are answered.
- [ ] {middle_name} is missing from the child's name
- [ ] Reduce the font size, so that child's name, age, and gender fit on one row. 
- [ ] Let's add a comma between child's age and gender
- [ ] Reason field should be required and have an asterisk
- [ ] Change the lower constraint error message on moved away date to "Moved away date cannot be before date of birth"
- [ ] Change label to "Date of death" instead of Date the family member died.
- [ ] Age at death note in the data dictionary was missed. See row 9 in the data dictionary for this form.

**Comment by cagulas** [comment]
QA 15 Feb release:

- [ ] The constraint logic is still not implemented correctly for date of death and date moved away fields:

For date of death: {date_moved} >= {dob} AND <= {today}
For date moved away: {date_died} >= {dob} AND <= {today}

Right now the constraint is that you have to record today's date only. You can't change it to anything else.

**Comment by mahmud6390** [comment]
Yeah getting the issue.Right now form min_date set logic is min_date=today-(no of year).
If the child age is less then 1 year then min_date showing today.
Need help to implement it.

**Comment by mahmud6390** [comment]
fixed added in https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/127

**Comment by cagulas** [comment]
Lgtm
