### ISSUE TITLE
Add Remove Family Member form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#37]
- [x] The Remove Family Member form is available from either the floating action button on the family member's individual profile page, OR from the family profile page, "Remove existing family member" option, then select that member in the screen.
- [x] Follow the content in the [data dictionary](https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=1085543306), "Remove Family Member" tab. This should also be the name of the form.
- [x] If the removal reason is that the person died, then the profile is still removed, but the person still appears in the family profile view. See https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/21 for more info. The person's profile picture should be removed, and the age at death (auto-calculated in this form) should be displayed.

<img width="372" alt="screen shot 2018-12-05 at 12 10 31 pm" src="https://user-images.githubusercontent.com/3488986/49502733-c89f7680-f886-11e8-8375-1c4105988d22.png">

- [x] In the above mockup, the back arrow (or tapping the device back button) takes the user back to the screen they were on before opening the form.
- [x] The SAVE button only becomes highlighted and tappable after all of the required fields in the form are answered.
- [x] Instead of "Remove member", use "Remove Family Member" as the form title at the top.

**Comment by rkodev** [comment]
Reported QA issues is being worked on here https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/35

**Comment by cagulas** [comment]
QA 7 Feb release:

- [ ] Let's decrease the space between the back arrow and the form title. Form title is getting cut off. We can also decrease the font size, so that it fits on one row. We can also shift the button slightly to the right.
- [ ] Let's change the Remove button to "Save"
- [ ] The Remove button shouldn't be bold font until all required fields are answered. Right now, it's bold as soon as you open the form.
- [ ] Reason field should have an asterisk, as it's a required field.
- [ ] Date of death is required so should have an asterisk.
- [ ] Is the date moved away and the date of death constraints at 10 years @rkodev ? The lower constraint should be the person's dob. Please check the data dictionary carefully.
- [ ] Age at death calculation and note are missing.

**Comment by rkodev** [comment]
@cagulas new version of the Forms Library hides the save button till all the required fields are entered. This also gives more room for the form title. 
The title toolbar is a native android view and the distance between the back button and the title has been reduced to the lowest value. It might take some time to develop a custom view for this form. Maybe next release

**Comment by cagulas** [comment]
Lgtm
