### ISSUE TITLE
Add Remove Family form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#38]
- [x] From this screen (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/28) the user can select remove the entire family, which launches the "Remove Family" form.
- [x] Follow the content in the [data dictionary](https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=1085543306), "Remove Family" tab. This should also be the name of the form.
- [x] No mockup provided for this, but use the template from https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/37 as necessary. 
- [x] Once the family is removed, the entire family record is removed from the family register list. In addition, any children who are part of that family who are in the child register list are also removed.

**Comment by faith-mutua** [comment]
QA 30 Jan:

- [ ] Removing an entire family does not remove children who are part of that family from the child register list. A user can still record visits for such children even though their family record has already been removed.

**Comment by rkodev** [comment]
Resolved

**Comment by cagulas** [comment]
QA 7 Feb:

- [ ] Let's reduce the space between back arrow and remove family form title
- [ ] Remove button doesn't have to be bold and the right margin can be reduced. It shouldn't be highlighted until all required fields are answered in the form.
- [ ] Reason is a required field, so it should have an asterisk.
- [ ] We can make the X adults and X U5 children the same font size as the family name.

**Comment by rkodev** [comment]
New form library behavior disables the button till all required fields are filled
Reduced to minimum distance between the back button and the title on the toolbar shipped by android. Next release for the 'Native Forms' library will include a custom toolbar

**Comment by cagulas** [comment]
Closing this and moving remaining QA to new issue.
