### ISSUE TITLE
Implement floating action button actions on individual profile pages

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#39]
Every family member in the app, not just under 5 children, will get a profile page. For the other family members (i.e. anyone older than 5), the page will mostly be blank, since they won't have scheduled home visits or any services due. They will have the floating action button, though. See below. These will be the same three actions for any family member in the app, including U5 children.

<img width="370" alt="screen shot 2018-12-05 at 3 08 51 pm" src="https://user-images.githubusercontent.com/3488986/49512783-08268c80-f8a0-11e8-904a-968d07f548b9.png">

The floating action button allows them to:
- [x] Call the family head and/or primary caregiver in the family - https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/25
- [x] Access the registration information, i.e. this launches their original registration form, allowing them to make edits (only to fields marked as Editable in the data dictionary)
- [x] Open the removal form to remove the family member - if it's an U5 child, it opens the https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/35 form, and if it's a person aged 5 or over, it launches the https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/37 form.

**Comment by mahmud6390** [comment]
working on this

**Comment by mahmud6390** [comment]
@rkodev please check this branch "individual-profile-floating" for this

**Comment by rkodev** [comment]
@mahmud6390 on this issue the option for is_primary_giver should be disabled when editing the profile for the primary care giver. It should only be enabled when editing profiles for other members to prevent the scenario where a family has no primary caregiver. @cagulas @keymane  your thoughts?

**Comment by cagulas** [comment]
@rkodev Yes, what you described makes sense to me. We do need to avoid the situation where there's no primary caregiver in the family, so if someone is already marked as the primary caregiver, we should not allow them to say no primary caregiver when editing their registration form.

**Comment by mahmud6390** [comment]
adding in pending PR https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/117

**Comment by cagulas** [comment]
Lgtm
