### ISSUE TITLE
Proposed list of sort/filter options

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#4]
**Families Register:**

Most recently updated (default)

Most recently visited
Last recently visited

Family name (A to Z)
Family name (Z to A)

**Child Clients Register:**

Most recently updated (default)

Most recently visited
Last recently visited

First name (A to Z)
First name (Z to A)

Last name (A to Z)
Last name (Z to A)

Age (youngest to oldest)
Age (oldest to youngest)

**Filter (both registers):**

Not visited this month

**Comment by rowo** [comment]
@cagulas these seem hard to understand, especially "Last recently visited". Perhaps we can take another approach where we assume what the sort is is being shown first:

Sort by
- Recently visited
- Not seen 
- Family name (a to z)
- Family name (z to a)

Or alternatively:

Sort by
- Previous visit date (recent first)
- Previous visit date (oldest first)

Also I'm assuming that we don't need both updated and visited. I always felt those were the same for CHWs in West Africa context.

**Comment by cagulas** [comment]
@rowo I do see a difference between updated and visited. Visited means they completed and submitted the home visit form. Updated could me they added a family member, or they changed family head, or they marked someone's record as closed. All of these are updates without having completed a home visit. 

As a compromise, do you think it's ok for us to say that previously visited also includes these updates? Because, in reality, they'll most likely make these updates in the context of a visiting the home. 

"Not seen" isn't really a sort, but more of a filter. What do you think about my earlier suggestion foor having a filter for "not seen this month"?

My preference is for previous visit date (recent and oldest first) instead of recently visited.

**Comment by rowo** [comment]
@cagulas Re: visited/updated. I don't feel strongly about if it should just home visits or any medical field edit or just any edit in general. The main thing is having both seems unnecessarily exact to me and probably not clear to most users. I think it's up to you how we should define it — but ideally I think just one approach would be nicer.

Re: not seen. Another term for this might be "Haven't seen recently" or "Not seen recently". It was just another wording for "least recently visited". Sometimes sort labels aren't completely correct as long as they get the point across. But looks like wording on this one is tough.

Re: filter. I don't think we should do sorts and filters. I'm apprehensive about even having sort as I think only a small percentage of CHW powerusers trying it — I think this is something we talked about from TZ feedback. That said, I like filters more than sort. With sort, lists with pagination are too difficult to scroll and so it'll probably be just a list of individuals that share the same status for pages and pages unless it's the 1st or last of the month. Also, the pagination is not optimized so even alphabetical is not useful — a search lookup is much much more likely. So, I propose:
- We don't any sort options. It just stays on [visited/updated] recent to oldest
- We have a filter for "not seen this month", which is basically the same as the quick filter in ZEIR with "show all due/overdue". For the reasons above, I think this will only be useful towards the end of the month.
- I want to (but won't) suggest having a "not seen in 2 [or 3?] or more months" filter. Options are complicated and we should focus on the main workflow. As the "not seen this month" list dwindles down, these extra-overdue individuals should start appearing on page 1 anyways.

To me, it sounded like the most useful thing for a CHW would be trying to figure out how to do a local area filter. I know we won't have the local level in the location hierarchy, but I feel like websites handle this sort of thing with user-typed tags and autocorrection. @keymane do you auto-suggest based on historical entries would be hard? Basically, entries in a string field get stored in the OpenSRP server (associated with the CHW) and it auto-suggests for future registrations typing the same field. Then it's also searchable in the register search box, which I'm assuming this field will be anyways. Main difference here is the auto-suggest to cut down on misspellings.

**Comment by cagulas** [comment]
@rowo Ok, I'm ok with your suggestions, i.e. don't have a sort menu, but everything in the list is default-sorted by last visited/updated (wording TBD), then have a filter for "not seen this month". With the default-sort, though, this means that when they do filter the list, the most recently updated records will appear on top, which means the "last seen 2 to 3 months ago people" will always be at the bottom, but I guess this is ok for now.

I will have to run this by the client, as we have listed other sort/filter options in the project brief that they may still want to have. @rowo If you can prepare the mockup for this, I'll use that to update them.

@keymane Interested to hear your thoughts about the auto-suggest for the location...I think this would be extremely useful in the absence of their location hierarchy, but it depends on how difficult this is to implement.

**Comment by keymane** [comment]
@rowo @cagulas  Yes, this is possible using https://developer.android.com/reference/android/widget/AutoCompleteTextView  but a bit expensive to implement. Which fields will have this feature and will be in the form or the search box..

**Comment by cagulas** [comment]
@keymane I think the proposal is that it would be one field initially, in the Family Registration form - {village_town}. How expensive is expensive?

**Comment by rowo** [comment]
@keymane @cagulas Update is on https://marvelapp.com/9j1277a/screen/48411528. The search conversation for village_town should be discussed but maybe in a new issue or offline. I do think it is really important. 

Maybe at a bare minimum, not even having an auto-complete would be okay, and we just make sure the village_town is part of the searchable fields would be helpful if it wouldn't overload the phone.

**Comment by cagulas** [comment]
Ok cool, will create a separate issue for this.
