### ISSUE TITLE
Ability to search by village_town in dynamic search

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#40]
This issue is to discuss the feasibility of including the {village_town} Text field from the Family Registration form in the dynamic search in both registers.

The advantage of this is obviously that the CHW plans his/her visits to villages and does home visits in specific areas on specific days, so having a way to filter the list to show specific areas would be helpful. The problem is that we are not getting a full location hierarchy from the client; due to resourcing and other operational constraints, this won't be possible at this point in time. This means that the location field in the Family Registration form will be a text field {village_town}. 

If it's a text field, we can count on the CHW making spelling mistakes, which will make the dynamic search difficult. To alleviate this problem, the suggestion is to implement an auto-correct field in the form, whereby they can easily select the village name based on previous entries.

Is this feasible? If the auto-correct is not feasible at this stage, can we still include village_town text field in the dynamic search?

**Comment by faith-mutua** [comment]
QA 29 January

Looks good to me
