### ISSUE TITLE
Implement due only filter in both registers

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#41]
In both register lists, there is a toggle button, see below, that filters the list of records to only those that have a currently due visit (either due or overdue).

<img width="353" alt="screen shot 2018-12-06 at 12 07 48 pm" src="https://user-images.githubusercontent.com/3488986/49574742-1fbe4d80-f952-11e8-8e40-7122a875ca57.png">
<img width="336" alt="screen shot 2018-12-06 at 12 08 08 pm" src="https://user-images.githubusercontent.com/3488986/49574751-2351d480-f952-11e8-9fad-b5e52d7043a1.png">

In the above mockups, the default state is not filtered. So all records are listed in the default-sort pattern only. When the toggle is activated, the list filters to only those records with a current due or overdue (i.e. blue or red state). We still use the default sort for the filtered list.

This works the same in both family and child register lists.

The filter toggle is kept active until the user toggles it back to see the full list, or until they exit the app.

**Comment by cagulas** [comment]
QA 21 Jan:

- [ ] The UI has been implemented, but not the functionality.

**Comment by faith-mutua** [comment]
QA 29 Jan: 

Functionality has been implemented
