### ISSUE TITLE
Implement widget to confirm closure of person's record

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#42]
For all family members, including children, and also for the entire family, when you tap the save button to submit the remove member or remove family form (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/35) and (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/37) and (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/38), the below widget pops up to confirm they want to close the record for this person (or the entire family):

<img width="332" alt="screen shot 2018-12-06 at 12 48 54 pm" src="https://user-images.githubusercontent.com/3488986/49576143-71b4a280-f955-11e8-83d1-8684af1d29f0.png">

Please use the below labels instead of what you see in the above mockup:

For Child and other Family Member:

Are you sure you want to remove {first_name} {middle_name} {last_name}'s record? This will remove their entire health record from your device. This action cannot be undone.

For entire family:

Are you sure you want to remove the {fam_name} Family's record? This will remove the family's entire record AND all of the {fam_name} family members' health records from your device. This action cannot be undone.

- [x] The Cancel button or tapping outside the widget will take the user back to the form.
- [x] The Remove button will proceed and remove the record(s) from the register lists.
- [x] After removal, the user is taken back to the register list screen they were previously on (either child or family).

**Comment by faith-mutua** [comment]
QA 30 Jan: 

- [ ] The text in both confirmation widgets are truncated. Tested this on Samsung J5 Duos.

**Comment by faith-mutua** [comment]
QA 05 Feb

lgtm

**Comment by cagulas** [comment]
QA 7 Feb release:

- [ ] This was implemented incorrectly. This should pop up after the user taps on the Save in the close form. Right now it's popping up before you launch the form.
- [ ] Use medium font for all text, including the cancel and remove buttons.
- [ ] Let's increase the right margin slightly in these pop-ups. Right now, the text is too close to the edge.

**Comment by cagulas** [comment]
Spoke with @keymane and this we'll push to the next release (the one after Feb 14th release).

**Comment by cagulas** [comment]
Lgtm
