### ISSUE TITLE
Implement Home Visit button statuses on child's profile page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#44]
On the child's profile page (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/43), the visit buttons in the top row have various states:

<img width="347" alt="screen shot 2018-12-07 at 11 48 07 am" src="https://user-images.githubusercontent.com/3488986/49637281-fcf56d00-fa15-11e8-88ae-7f510d8eff33.png">

- [x] This is the starting state at the beginning of the month, when all children become due for a child home visit on the 1st of the calendar month. When a child is first registered, this will automatically be their profile page visit status.
- [x] The blue record visit button opens the child home visit page (separate issue to be created)
- [x] The white visit not done button allows the user to mark the visit was not done this month, which leads to the state below:

<img width="344" alt="screen shot 2018-12-07 at 11 50 37 am" src="https://user-images.githubusercontent.com/3488986/49637405-55c50580-fa16-11e8-9fcf-b15002b9fc8a.png">

- [x] In the above, if the user taps on Undo, the button state returns to whichever state the due visit was in before (either due, like above or overdue, like below).

<img width="337" alt="screen shot 2018-12-07 at 11 51 51 am" src="https://user-images.githubusercontent.com/3488986/49637478-8b69ee80-fa16-11e8-8a48-ebfc2a1baf8b.png">

- [x] Above is the overdue state of the visit button.
- [x] Tapping on the red Record visit button launches the child home visit page (separate issue to be created). 
- [x] Tapping on the visit not done button again changes the visit state to the "Not visiting this month" status

<img width="353" alt="screen shot 2018-12-07 at 11 54 48 am" src="https://user-images.githubusercontent.com/3488986/49637613-ebf92b80-fa16-11e8-99f8-040248d4a0fb.png">

- [x] The above state is a temporary state only. For the 24 hours after a home visit is recorded, the user will see the above status. After 24 hours, the status changes (see next image below).
- [x] Use the calendar month that the visit was done in.
- [x] Tapping on the edit button launches the form that they submitted previously, where they can make edits.

<img width="377" alt="screen shot 2018-12-07 at 11 56 39 am" src="https://user-images.githubusercontent.com/3488986/49637696-2d89d680-fa17-11e8-983b-09e114f7650c.png">

- [x] Finally, the last state above, is the state after the 24 hour period that a form was submitted. This essentially allows the user to submit multiple home visits per month, even when the next home visit isn't due yet. 
- [x] Tapping on this button opens the child home visit form 
- [x] On the first of the next calendar month, the button status changes again and becomes blue (see first image in this issue).

**Comment by mahmud6390** [comment]
All status set when press home visit submit button.

**Comment by mahmud6390** [comment]
![device-2019-01-08-200818](https://user-images.githubusercontent.com/2793306/50835694-98655f00-1381-11e9-9b8c-8d3127bd9027.png)
>>multiple status based on home visit

**Comment by cagulas** [comment]
QA 21 Jan:

- [ ] the X icon shown when you select not visiting this month should be gold font, same as what's used as the visit not done font on the main register page.

**Comment by mahmud6390** [comment]
Add icon from asset folder activityrow_notvisited
At pending PR
https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/106

**Comment by cagulas** [comment]
Lgtm
