### ISSUE TITLE
Implement Child Medical History page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#46]
<img width="335" alt="screen shot 2018-12-07 at 12 03 58 pm" src="https://user-images.githubusercontent.com/3488986/49638105-45ae2580-fa18-11e8-9032-cf628d59f04b.png">
<img width="331" alt="screen shot 2018-12-07 at 12 04 06 pm" src="https://user-images.githubusercontent.com/3488986/49638106-4646bc00-fa18-11e8-9086-28a72ef552fd.png">

- [x] This page opens when the user taps on the Last visit XX days ago / medical history row in the child's profile page (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/43).
- [x] Top back arrow takes you back to child's profile page. Use the child's name in the label. 
- [x] This back arrow is anchored on scroll (see 2nd image above).
- [x] Three sections are: Last Visit; Immunizations; and Growth and Nutrition
- [x] Last visit shows how many days ago the last visit was. Label to use: "XX days ago". @rowo I don't think we need to say the "for home visit (on time) part". I don't think it matters to them. Is this ok?
- [x] For immunizations and growth & nutrition sections, refer to the data dictionary, Child Home Visit tab, for the order and sequencing of the services. For the groupings, you can see how the immunizations are grouped in the data dictionary. You can use "Birth" "6 weeks" "10 weeks" for the headings on this page, as seen in the mockup above. 
- [x] The exception to the above is that the fully immunized badges are placed at the top of the immunization section, 2 yr fully immunized above 1 yr fully immunized (separate issue to be created).
- [x] The immunization and growth & nutrition services only show up when they're done. So this is essentially their medical record that grows over time.

**Comment by rowo** [comment]
Marvel prototype: https://marvelapp.com/9j1277a/screen/48904521

**Comment by rowo** [comment]
@cagulas For the last visit rules — yes, if the user is only ever going to receive a home visit (like in this specific case), they wouldn't need the other parts. However, for consistency across projects that may involve more than one type of visit, it is probably useful information. I think this is similar to the family activity, so matching up with that content could be good.

**Comment by mahmud6390** [comment]
![screenshot_2019-01-08-19-57-30-408_org smartgresiter wcaro](https://user-images.githubusercontent.com/2793306/50835175-3c4e0b00-1380-11e9-93cd-9f8f473db762.png)
>> working on fully immunized at age part.
>>After input growth and nutrition it'll show in this screen

**Comment by cagulas** [comment]
@mahmud6390 I think this page is broken in the app. I tap on the row and nothing happens. I can't open it for any child.

**Comment by faith-mutua** [comment]
QA 05 Feb

- [ ] The fully immunized badge isn't shown for a child of 2 years who has been fully immunized.

**Comment by mahmud6390** [comment]
Add this in pending PR
https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/106

**Comment by cagulas** [comment]
Closing this and opening a new issue for QA
