### ISSUE TITLE
Implement the service schedules for all child home visit services

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#50]
The [service schedules spreadsheet](https://docs.google.com/spreadsheets/d/1DI_H61RN7R07m9FD2DyFauqg0XrxP7r3afW3qoNh8So/edit#gid=171283311) (see the "Child Home Visit Services" tab) lists the scheduling logic (due, overdue, expiry) for all of the services that need to be listed in the child home visit page. All of these services are only considered complete when the service is given. So, if a service is marked as not given or not done during a home visit, it remains due/overdue, and will show up in the next home visit, etc. until it is either given or expired.

**Comment by cagulas** [comment]
@raihan-mpower I'm not seeing Birth Certification and Observations and Illness Episodes services in the home visit form. See the data dictionary, Child Home Visit tab, rows 78 and 87 (https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=1775888911). Are these not implemented yet?

**Comment by raihan-mpower** [comment]
@cagulas there is a pending PR with these implemented.
https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/93

**Comment by faith-mutua** [comment]
QA 05 Feb

lgtm

**Comment by cagulas** [comment]
Reopening this as a result of QA on 7 Feb release:

- [ ] For child "Martha Carolyn, 8w", the birth immunizations should be showing as overdue and in red font in the home visit screen, but right now, they're showing as Due 14 Dec 2018. It should say "Overdue (14 Dec 2018)" instead and in red font.
- [ ] Same thing with Exclusive breastfeeding 0 months. This is now overdue and should be showing overdue.
- [ ] Birth certification shouldn't be due until 12 months of age, but right now, it's showing up for child Martha Carolyn who is only 8 weeks old.

**Comment by cagulas** [comment]
Created a separate issue with all remaining QA. Closing this.
