### ISSUE TITLE
Implement Child Home Visit page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#51]
When the user taps on the home visit button on the child's profile page (or on the main child register page), they land on this page:

<img width="337" alt="screen shot 2018-12-07 at 3 09 20 pm" src="https://user-images.githubusercontent.com/3488986/49647236-d0038300-fa32-11e8-8cbd-c2ae507a90c2.png">

- [x] Top left X button cancels the home visit and returns the user to the page they were on before (i.e. the child profile page)
- [x] Before they exit, we need to add a confirmation close message saying that any information they entered will be lost (we can use one of the existing form close confirmation messages from OpenSRP)
- [x] Submit button remains greyed out until all required questions in the home visit are answered at a minimum.
- [x] Form title is: "`first name` `middle name` `last name`, `age`· Home Visit"
- [x] The thing between age and form name is an interpunct or middle dot. A comma is okay if you want to be less fancy.
- [x] Only the services that are due/overdue are shown (refer to https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/50 for the scheduling logic for the services)
- [x] Tapping on the row or the circle next to the service opens the widget for the user to record that service was given (or not) - separate issues to be created
- [x] If the service is due, show the due date in grey font (as pictured - Immunizations 14w)
- [x] If the service is overdue, show the due date in red font (as pictured - Penta 1)
- [x] If the service doesn't have a due date (e.g. birth certification and observations and illness episodes, as examples, then don't show a due date (e.g. "Development" in the mockup above)
- [x] Vaccinations are grouped by age group (see data dictionary for these groups)
- [x] When single vaccinations are due (e.g. one vaccine wasn't given from last time), then it's listed singly (see Penta 1 in mockup above)
- [x] In general, see the bold, grey highlighted rows in data dictionary, Child Home Visit tab, for the labels to use here.
- [x] Note that some of these will be single services (e.g. Penta 1, above), while others will be a series of questions (e.g. Observations & Illness episodes)

**Comment by cagulas** [comment]
@raihan-mpower @mahmud6390 

<img width="592" alt="screen shot 2019-01-10 at 1 15 43 pm" src="https://user-images.githubusercontent.com/3488986/50961874-ebeac080-14d9-11e9-9783-b602af0ab0c3.png">

- [ ] The Submit button should be all caps and try to match the font size and color better to the mockup and increase the right hand margin so it’s not right up against the side. Increase the height of the top section if needed (see mockup). Increase the left hand margin for the top left X button and child’s name.
- [ ] The color might be off since this is a screenshot, but let’s try to match the top blue color better.
- [ ] Spacing issues again (add space between immunizations and 6 weeks)
- [ ] We should be showing the due date for the vaccines, not listing the vaccines that are due. See mockup.
- [ ] Abbreviate weeks to “w”. See mockup.
- [ ] OPV 1 is missing the due date underneath
- [ ] The font size of the due items can be increased a size or two. The circle can also be enlarged sligthtly.

**Comment by mahmud6390** [comment]
middle name added in pending PR
https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/106

**Comment by cagulas** [comment]
@mahmud6390 @raihan-mpower What's the status of the QA above? Can you work on the remaining QA items? Are the ones that are checked supposed to be in the 7 Feb release, because I'm not seeing them?

Also these:

- [ ] Remove "On" so it just reads "Due 14 Dec 2018" (instead of "Due On 14 Dec 2018")
- [ ] For exclusive breastfeeding, it should show the due date instead of repeating exclusive breastfeeding. So, the first line should read "Exclusive breastfeeding 0 months" and the next line should read "Due 14 Dec 2018" for example.
- [ ] We don't need to add "Report" as a prefix to all of these data entry forms. For example, for Birth Certification, the form title can just be "Birth Certification" and not "Report Birth Certification". It's getting cut off right now, so removing this should help.
- [ ] For the Birth certificate issuance date field, it seems like there's a constraint that only today's date can be selected. Please check the data dictionary. It should be constrained by the child's DOB and today's date.
- [ ] The note "Instruct the caregiver to have the birth registered with the civil registrar." still appears even if you back and change your answer at the beginning.
- [ ] Birth certiication is also missing a due date on the home visit screen.

**Comment by cagulas** [comment]
Closing this and moving all remaining QA to a new issue.
