### ISSUE TITLE
Implement multi-vaccine data entry widget

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#52]
<img width="337" alt="screen shot 2018-12-07 at 7 39 43 pm" src="https://user-images.githubusercontent.com/3488986/49660573-f7207b80-fa57-11e8-8bd7-8fd574997aa1.png">

- [x] In the child home visit page (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/51), clicking on any of the grouped vaccinations (e.g. Immunizations (14w)), a page like the above will open.
- [x] Instead of what's above in the mockup, use the labels from the data dictionary, i.e. if it's a group of vaccines, use "Which vaccinations were given?". I'm creating a separate issue for a single vaccine.
- [x] All of the vaccines are default-checked when the page opens, but the user can un-check any or all of them.
- [x] The label above the date widget should read "When were vaccinations done?"
- [x] The user can select the date, and that date gets recorded as the vaccination date for all of the vaccines that were checked.
- [x] In rare instances, the vaccines might have been given on different dates, in which case, the user can tap on the "Add date for each vaccine" and the question separates out into individual date inputs for each checked vaccine (no mockup provided for this).
- [x] Save button records the vaccinations and the dates, while "Vaccines not done" button records that none of the vaccines were given.
- [x] X button takes the user back to the home visit page without making any changes. We do NOT need a confirmation message on close for this. The user just goes straight back to the home visit page.
- [ ] Instead of "record immunizations" change the title to "Record vaccinations"
- [ ] Remember to check out the [data dictionary](https://docs.google.com/spreadsheets/d/1fznZZXQK9PNsvmAjzJjncFeO3qxN4NWmyPym7rbKQQ8/edit#gid=1775888911), Child Home Visit tab, for the required fields and the constraints to use on these fields.

**Comment by rowo** [comment]
- This isn't clear in the issue, but ideally the interaction after tapping "add date for each vaccine" is the the date question is replaced with individual date questions for each checked vaccine from the first question — staying within the same form. Back on the home visit main screen, the description would give the specific date for each vaccine, still in the same subline — not broken out like it is now.
- This is a funny interaction looking at it now. Coming back into this after answering gets weird when you want to change your answer, for example when "Vaccines not done" is initially selected, then you come back to select vaccines to "Save". I don't think it's possible now. We might want to change this and (1) treat the first question like the [danger sign question from ANC](https://github.com/OpenSRP/opensrp-client-anc/issues/40#issue-346835723) where a checkbox option is a "No vaccines not done" which is deselects the other boxes and (2) put only a Save button on the form.

**Comment by cagulas** [comment]
I'm closing this for now. We are discussing today if we need to re-design this interaction to resolve some of the confusion around this. Will create new issues for the outcome of the meeting.
