### ISSUE TITLE
Implement full screen multi-question widget

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#54]
<img width="361" alt="screen shot 2018-12-07 at 8 01 56 pm" src="https://user-images.githubusercontent.com/3488986/49661758-0654f880-fa5b-11e8-9391-72924bf8db02.png">

- [x] The above page is what you'd see if selecting certain services from the home visit page that are yes/no questions rather than date selections, e.g. Observations & Illness Episodes, or Birth Certification sections.
- [x] Use the exact content from the data dictionary, Child Home Visit tab, instead of what's shown in the mockup, which is out of date.
- [x] X button takes the user back to the home visit page without making any changes. We do NOT need a confirmation message on close for this. The user just goes straight back to the home visit page.
- [x] The Save button at the bottom becomes blue and tappable once all of the required questions at a minimum are filled in.

**Comment by cagulas** [comment]
QA 21 Jan:

- [ ] Add an "s" to months in the title
- [ ] Increase the font size slightly for the title. It should still fit in one row without spilling over though.
- [ ] Roger created icons for some of these questions. For breastfeeding, please use the one found in https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/10. Please add the image above the question label and answer choices.
- [ ] The answers that are provided are not getting populated in the home visit page (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/55). Here, the answer they provide yes/no should be displayed back on the home visit page. This isn't implemented yet. The tricky thing here is that if they answer "No" to the question, that means they are exclusively breastfeeding, so the answer shown in the home visit page should be "Yes" and vice versa.
- [ ] When you revisit the page, the answer is not being saved. So if I answer this question, then save and return to home visit page, then return to the question, the answer is no longer selected. The answers inputted should persist within the same home visit.

**Comment by mahmud6390** [comment]
https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/53
For e.g. for Vitamin A, the form title would be "Record Vitamin A dose" and the question would read "When was Vitamin A Nth dose given?", then there'd be "Save" and "Dose not given" buttons at the bottom.

**Comment by cagulas** [comment]
@mahmud6390 What's the status on this one? It's still in the To Do column in the project. Please move it to where it should be.

**Comment by cagulas** [comment]
Closing this and will put all remaining QA into new issue.
