### ISSUE TITLE
Implement Child Home Visit page with services recorded

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#55]
<img width="348" alt="screen shot 2018-12-07 at 8 21 03 pm" src="https://user-images.githubusercontent.com/3488986/49662737-b0ce1b00-fa5d-11e8-9807-16900e6bd4a8.png">

- [x] The above mockup is an example of what an in-progress child home visit page would look like. The first three services were recorded, while the last 3 services haven't been opened yet.
- [x] The yellow check icon indicates that they answered the questions, but that one or more of the services were marked as not given, while the green check icon indicates the questions were all recorded and all services were given. The white circle means they haven't answered the questions yet.
- [x] In light grey font below the service categories, list out the services that were given and the date they were given and the services that were not given.
- [x] I think instead of "provided", let's use the word "given" or "done. I.e. OPV 3 done on DDMMYYYY; Penta 1 not done, etc.
- [x] Top left X button cancels the home visit and returns the user to the page they were on before (i.e. the child profile page)
- [x] Before they exit, we need to add a confirmation close message saying that any information they entered will be lost (we can use one of the existing form close confirmation messages from OpenSRP)
- [x] Submit button remains greyed out until all required questions in the home visit are answered at a minimum.
- [x] Form title is: "first name middle name last name, age· Home Visit"
- [x] The thing between age and form name is an interpunct or middle dot. A comma is okay if you want to be less fancy.

**Comment by cagulas** [comment]
QA 21 Jan:

- [ ] Add a space between the vaccines and commas. Right now it shows "BCG,OPV 0" which is missing a space after comma and before OPV 0.
- [ ] A space is also missing in the above text: "Immunizations(at birth)" is missing a space before the parenthesis.
- [ ] The green check mark should replace the grey circle. Right now, it looks like the green check mark just fills the circle.
- [ ] Instead of listing just the vaccines, we are supposed to show "BCG provided on [date]". Please fix this. See the above original mockup.
- [ ] Similarly, if a vaccine is not provided within a group, we separate that vaccine with an interpunct, and say that it was not provided. See the above mockup again. So if BCG was given and OPV 0 was not given, we'd show "BCG given on [date] · OPV 0 not given".
- [ ] In the above scenario, the icon needs to be the yellow check mark, not the green.
- [ ] I'm noticing a weird bug whereby if you provide BCG and OPV 0, then save, then go back to the screen and un-select OPV 0 and save again, the BCG vaccine gets duplicated in the row.

**Comment by cagulas** [comment]
@raihan-mpower  What's the status on this one? It's still in the To Do column in the project. Please move it to where it should be.

**Comment by raihan-mpower** [comment]
@cagulas  updated to in progress in the project, there might still be an issue in secondary text of the single not given vaccines from last visit, the others should work properly

**Comment by cagulas** [comment]
Closing this and putting all remaining QA in a new smaller issue.
