### ISSUE TITLE
Implement login page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#6]
<img width="380" alt="screen shot 2018-11-24 at 1 58 04 pm" src="https://user-images.githubusercontent.com/3488986/48967967-0b449180-eff1-11e8-877c-3b9dc0df5da6.png">

We will be getting the app name and logo from the client hopefully soon. In the meantime, please call the app name "CFC" on both the login page and the app icon on the device. 

Show the version number and also the build data (which is not pictured).

**Comment by keymane** [comment]
Similar to https://github.com/OpenSRP/opensrp-client-anc/pull/143/files Most of the login base activities and views are in the https://github.com/OpenSRP/opensrp-client-core module

**Comment by cagulas** [comment]
Closing this, but please note: https://github.com/OpenSRP/opensrp-client-core/issues/148
