### ISSUE TITLE
Implement side menu of registers

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#7]
See side menu interaction on Marvel: https://marvelapp.com/9j1277a/screen/48411528

<img width="378" alt="screen shot 2018-12-05 at 10 03 34 pm" src="https://user-images.githubusercontent.com/1584163/49558631-bac71100-f8d9-11e8-9de3-4a62e55a7044.png">
<img width="374" alt="screen shot 2018-12-05 at 10 03 43 pm" src="https://user-images.githubusercontent.com/1584163/49558636-bd296b00-f8d9-11e8-985f-29f47ae56b62.png">

- [x] The side menu can be opened by swiping from the left or tapping the side menu button on the main register page (both family and child).
- [x] WCARO logo will be replaced with the logo they send
- [x] The number next to the registers is the total number of records in that register
- [x] Blue font for the register that's currently selected - Families should be default-select each time a user logs in.
- [x] Right now, we are only implementing the Families and Child registers, so do not show ANC or HIV for now.
- [x] Logout button shows user's first name and logs user out of the app
- [x] Message Roger for the icons when you are about to start work on this issue. RW: Icons will be developed at one time in https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/10. Mockup icons are placeholder but will be the same relative size.
- [x] Sync button attempts to sync in between automatic attempts. Last successful sync date and time also shown. We might have to discuss the meaning of sync when we implement device to device sync, but this should be ok for now.

**Comment by cagulas** [comment]
@rowo I forget what we agreed to. Do they come to this screen as soon as they login, or are they directed automatically to the Families Register?

**Comment by raihan-mpower** [comment]
is this something someone from our side can start working on>

**Comment by cagulas** [comment]
QA 4 January:

- [ ] The All Families register is not highlighted when you first log in to the app, even though you land on this register when you login.

**Comment by cagulas** [comment]
QA 21 Jan:

The only remaining thing to be implemented is the sync button and date & time:

- [ ] Sync button attempts to sync in between automatic attempts. Last successful sync date and time also shown. We might have to discuss the meaning of sync when we implement device to device sync, but this should be ok for now.
- [ ] Also, if possible, let's use an animated syncing icon when a sync is in progress.
- [ ] Remove the space between Last and the colon.

**Comment by cagulas** [comment]
@rkodev Just confirming this QA hasn't been addressed yet in this latest release (Feb 6th)?

**Comment by rkodev** [comment]
@cagulas not yet, this QA is be addressed on the next release

**Comment by rkodev** [comment]
@cagulas we already added a sync animation on the Family Register. Should we also animate the sync icon on the Navigation Menu?

**Comment by cagulas** [comment]
@rkodev There is no sync button on the family register page in the top right corner, so I could see this being confusing to the user when the sync animation shows up there when there's nothing there at other times. Ideally, the sync animation is only on the side menu where the sync button is, especially as this is also where the last sync information is displayed. Is this easy to change?

**Comment by rkodev** [comment]
@cagulas The animation on the register has been removed. Moved it to the Navigation Menu

**Comment by cagulas** [comment]
@rkodev Brilliant!

**Comment by cagulas** [comment]
Closing this and moving all remaining QA to new issue: https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/120
