### ISSUE TITLE
Replace app name

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#78]
We have confirmation of the app name now:

Liberia CFC Monitor

We can abbreviate this to "Liberia CFC" for the app name below the app icon on the app menu page if needed, but if it fits, please use the full name.

Please also replace "WCARO LOGO" on the side menu with the app name.

**Comment by faith-mutua** [comment]
QA 30 Jan:

**Comment by cagulas** [comment]
Reopening this. We swapped the words. It should be "Liberia CFC Monitor" and not "CFC Liberia Monitor"

**Comment by rkodev** [comment]
Resolved

**Comment by cagulas** [comment]
Lgtm
