### ISSUE TITLE
App logos

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#79]
Pls let me know if more high res images are required.

![liberia-logo](https://user-images.githubusercontent.com/3488986/51461097-4e5f7e80-1d6e-11e9-9060-e3669999e373.png)
![unicef_logotype_cyan_cmyk_300ppi_eng-fr-sp](https://user-images.githubusercontent.com/3488986/51462058-c4fd7b80-1d70-11e9-8332-5ccc6c612976.JPG)

Both should be of equal size (approximately) on the login page, side by side.

The Liberia logo can be used as the app icon.

**Comment by rowo** [comment]
@rkodev Here is a combined logo image. It's on a white background though since that's what was provided, but let me know if you need something on transparent

![wcaro-logo-white](https://user-images.githubusercontent.com/1584163/51789893-13898c00-215c-11e9-9a5b-0bb5fe1eeef6.png)

**Comment by rkodev** [comment]
![screenshot_1548936639](https://user-images.githubusercontent.com/43806892/52053535-a5353700-256a-11e9-884d-683094740aeb.png)
See attached screen shot.
@cagulas  @rowo It would be better to make the images lay one over the other.

**Comment by rowo** [comment]
@rkodev I'm okay with one over the other. I was not involved in the side by side requirement. Could you: 
- change the background to #F6F6F6
- use the below logo file
- update the styling to be on the light grey background (show below)? It is what is being used for Reveal if you can just reuse that. Manu or Vincent might be able to help — they have touched the Reveal login view

![wcaro-logo](https://user-images.githubusercontent.com/1584163/52084882-0d871700-2571-11e9-94b9-00c610c7da91.png)

@cagulas Does the login page need an app title? See below examples of with and without.

![log in - wcaro-a](https://user-images.githubusercontent.com/1584163/52084921-30b1c680-2571-11e9-93e8-a93a87f7d5fc.png)

![log in - wcaro-b](https://user-images.githubusercontent.com/1584163/52084929-33acb700-2571-11e9-8332-44092772b0d8.png)

**Comment by rowo** [comment]
![wcaro-logo](https://user-images.githubusercontent.com/1584163/52186810-c65e8780-27f7-11e9-9fd8-fd9a1de54ad7.png)
![log in copy 2](https://user-images.githubusercontent.com/1584163/52186811-c65e8780-27f7-11e9-8fed-c2bbc811920c.png)

**Comment by cagulas** [comment]
6 Feb release:

Lgtm. 

@rowo They are side by side, which is fine with me, but I see you've updated it to the above. Do you mind if it's side by side?
