### ISSUE TITLE
Update back arrow label on child profile page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#83]
If you navigate to a child's profile page from the family member's page, the top left back arrow on the child's profile should say "Return to family members" instead of "Return to all children"

**Comment by cagulas** [comment]
@mahmud6390 It doesn't look like this fix made it into this 14 Feb release...

**Comment by mahmud6390** [comment]
yeah i think it's reverted from code.will be add in future,as pending PR already approved.

**Comment by cagulas** [comment]
Ok, no problem.

**Comment by mahmud6390** [comment]
Fixed pending PR https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/127

**Comment by mahmud6390** [comment]
![device-2019-02-22-010945](https://user-images.githubusercontent.com/2793306/53195105-2306d280-363f-11e9-8f77-75a514dd7de7.png)
text change if comes from family profile
